### ISSUE TITLE
exceptions not set on pending futures

### ISSUE THREAD

**Issue by daef** [gmarull/asyncqt#10]
Basically I have the same issue as this @hartytp in https://github.com/harvimt/quamash/issues/109 , which is already fixed in https://github.com/harvimt/quamash/pull/113

Am I supposed to use quamash over asyncqt? Is asyncqt dead?

Also possibly related: https://github.com/harvimt/quamash/issues/91

**Comment by gmarull** [comment]
Fixed by 651f9227e8f50f3742ff61d291e7a2b30dd0fadc
