### ISSUE TITLE
asyncSlots are not awaitable

### ISSUE THREAD

**Issue by syamajala** [gmarull/asyncqt#14]
The wrapper for the asyncSlot decorator never returns the future it creates and just returns None. This means you cannot await asyncSlots.

The issue is here:
https://github.com/gmarull/asyncqt/blob/master/asyncqt/__init__.py#L644

It should be returning the future.

**Comment by TheGreatCabbage** [comment]
@gmarull Good to see that you're asyncqt is active again!

This issue was fixed in `qasync` at CabbageDevelopment/qasync#5, and I'll happy to send the fix upstream tomorrow.

**Comment by gmarull** [comment]
Thanks @TheGreatCabbage
