### ISSUE TITLE
Support get_running_loop()

### ISSUE THREAD

**Issue by niklasf** [gmarull/asyncqt#3]
`asyncqt` should set the event loop as running, while it is running. There is an internal API `asyncio.events._set_running_loop()` in earlier/all(?) versions and `asyncio.get_running_loop()` is exposed since Python 3.7.

Example:

```python
import asyncio

from PySide2.QtWidgets import QApplication
from asyncqt import QEventLoop

async def print_running_loop():
    print("loop:", asyncio.get_running_loop())

asyncio.get_event_loop().run_until_complete(print_running_loop())

print("---")

app = QApplication()
loop = QEventLoop(app)
asyncio.set_event_loop(loop)
loop.run_until_complete(print_running_loop())
```

Output:

```
loop: <_UnixSelectorEventLoop running=True closed=False debug=False>
---
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    loop.run_until_complete(print_running_loop())
  File "/home/niklas/Schreibtisch/asyncqt-running-loop/venv/lib/python3.7/site-packages/asyncqt/__init__.py", line 302, in run_until_complete
    return future.result()
  File "example.py", line 7, in print_running_loop
    print("loop:", asyncio.get_running_loop())
RuntimeError: no running event loop
```

**Comment by niklasf** [comment]
This is becoming more important, now that Python is deprecating passing the loop around explicitly (https://bugs.python.org/issue36373).

**Comment by TheGreatCabbage** [comment]
> This is becoming more important, now that Python is deprecating passing the loop around explicitly (https://bugs.python.org/issue36373).

Since my pull request (referenced above) wasn't merged, I forked `asyncqt` and implemented the fix there. You may find [qasync](https://github.com/CabbageDevelopment/qasync) useful.
