### ISSUE TITLE
Any example of mixing QThreadPool and asyncio?

### ISSUE THREAD

**Issue by stereomatchingkiss** [gmarull/asyncqt#4]
As the title mention. Exactly it do not need to be QThreadPool, I just need a way to dispatch the request I received from the websockets into a thread pool. What is the correct way to do that? 

I would like to use QWebSocket and QWebSocketServer directly so I could use the Qt way to handle the events and multi-thread tasks, but QWebSocketServer  of PySide2 do not work with ssl(on windows), you can check this [link ](https://forum.qt.io/topic/101875/do-websocket-module-of-pyside2-support-ssl)if you were interested. 

ps : I am sure the c++ and python version load the same dll, both of them are Qt5.12.2

**Comment by Bomberus** [comment]
Hi, so I was kinda interested in the same topic.
Does this gist solve what you are looking for: https://gist.github.com/Bomberus/0000ef0d56ee0aac285d9e2045452b0b ?

**Comment by Bomberus** [comment]
Here is an example using asyncio with QThreadExecutor. For each thread a new event loop is created. If you need to make UI updates, trigger them over main loop.

https://gist.github.com/Bomberus/0000ef0d56ee0aac285d9e2045452b0b

**Comment by gmarull** [comment]
Closing as an example has been provided, thanks @Bomberus
