### ISSUE TITLE
Extend QThreadExecutor example for concurrent asyncio operation

### ISSUE THREAD

**Issue by Bomberus** [gmarull/asyncqt#5]
Here is an example using asyncio with QThreadExecutor. For each thread a new event loop is created. If you need to make UI updates, trigger them over main loop.

https://gist.github.com/Bomberus/0000ef0d56ee0aac285d9e2045452b0b

_Originally posted by @Bomberus in https://github.com/gmarull/asyncqt/issues/4#issuecomment-491630354_

**Comment by gmarull** [comment]
Closing, feel free to open a PR with the example if you want it included.
